### ISSUE TITLE
مسافات بين الحروف

### ISSUE THREAD

**Issue by msabryamin** [Gue3bara/Cairo#14]
![capture](https://cloud.githubusercontent.com/assets/3315322/21954597/4e8f7f54-da5e-11e6-8786-d65c88294a23.PNG)

**Comment by Gue3bara** [comment]
This issue is only in the version available on Google fonts right now but i already solved it and waiting for google engineers to update to the latest version on Github
<img width="1114" alt="screenshot 2017-01-14 15 57 51" src="https://cloud.githubusercontent.com/assets/12478169/21955353/3ecde6dc-da72-11e6-9916-d5a26d3cf096.png">

**Comment by Gue3bara** [comment]
@davelab6 when do you think the version on the servers can be updated been a long time

**Comment by davelab6** [comment]
Hopefully in q1
