### ISSUE TITLE
Letter Style Difference Compare to Google Font Version

### ISSUE THREAD

**Issue by sunilnizar** [Gue3bara/Cairo#21]
Hi
We used the Google version of Cairo font before and we were facing the letter-spacing issue in windows. But in the GitHub version, the issue is not there and found much better in both Windows and Mac.
But in the Github version, some of the characters are in a different style:

Here Google font version:
<img width="80" alt="screen shot 2017-12-10 at 3 47 49 pm" src="https://user-images.githubusercontent.com/5804325/33804627-42c2d7a8-ddc2-11e7-9c95-faea61eb311d.png">

Here the Gibhub version:
<img width="100" alt="screen shot 2017-12-10 at 3 47 01 pm" src="https://user-images.githubusercontent.com/5804325/33804634-5dc91cce-ddc2-11e7-9dd1-28dc6bebbc0c.png">

Please advise if this is a different style of writing or a bug.

**Comment by Gue3bara** [comment]
Hello
what you noticed here is the use of ligature its alternative ways for glyphs to connect in arabic, 
i did it as an upgrade after solving the spacing issue 
I just pushed a new version now without the ligatures forced, only available optional because i feel it's confusing the users not being so familiar to it 

Anyways a new upgraded revised version of Cairo will be available very soon here and on Google Fonts so stay tuned please
