### ISSUE TITLE
Kerning issues in Windows

### ISSUE THREAD

**Issue by annakelian** [Gue3bara/Cairo#24]
Hi @Gue3bara ,

I'm using Cairo from the Google CDN on a website of mine, and I had visitors on Windows report that the font is broken on Chrome and Firefox in Windows. Here are screenshots they sent:

On Chrome:
<img src="https://cl.ly/070l3O0q0A1K/Screen%20Shot%202018-03-10%20at%2010.57.03%20AM.png" />
<img src="https://cl.ly/2t20290p0k2i/WhatsApp%20Image%202018-03-05%20at%208.45.59%20PM.jpeg" />

On Firefox:
<img src="https://cl.ly/3a3O2u3R442u/WhatsApp%20Image%202018-03-05%20at%209.26.08%20PM.jpeg" />

Is there a fix for this?

**Comment by Gue3bara** [comment]
Hello @annakelian The issue you are experiencing is in an old version of Cairo and is fixed in the recent release available in the [Git](https://github.com/Gue3bara/Cairo/tree/master/fonts) but still not on Google fonts but will be updated there soon 
<img width="891" alt="screenshot 2018-03-10 22 40 44" src="https://user-images.githubusercontent.com/12478169/37246578-a4e94a5a-24b4-11e8-8b66-e9aa9198bd1b.png">

@davelab6 another issue that was solved in the recent releases any idea when @m4rc1e will be pushing the recent release?

**Comment by annakelian** [comment]
Any updates @Gue3bara @davelab6 @m4rc1e ?

**Comment by m4rc1e** [comment]
Looking into it today.

**Comment by annakelian** [comment]
Hey guys. Is this resolved?

**Comment by m4rc1e** [comment]
#27 is fine, awaiting merge
