### ISSUE TITLE
Contour/component collisions

### ISSUE THREAD

**Issue by m4rc1e** [Gue3bara/Cairo#26]
From the latest release

![alt text](https://camo.githubusercontent.com/06610549715f612929daad99788978b6f662fec2/68747470733a2f2f692e696d6775722e636f6d2f53347773526e592e676966)

Also, I feel the Black may be too dark in comparison to the previous GF release.

Feel free to finish anything else in my sandboxed pr:
https://github.com/m4rc1e/fonts/pull/42

cc @davelab6

**Comment by Gue3bara** [comment]
will check on the issues like "multiply" and other glyphs where it's a Glyphs bug that randomly misses with the path direction causing such issues 

Regarding the Black weight
In October 2017 I finally got the source for the latin Titillium to use it to fix the kerning and update the arabic to go accordingly so we have one font family on GF under Titillium supporting arabic instead of having Titillium & Cairo
And according to the new sources I had to redo the black weight in a whole new master and it's darker than the previous GF release only to match with the latin black master

**Comment by Gue3bara** [comment]
@m4rc1e The edits are done but I'm not sure how to update them on pr 
it says i dont have an access 
<img width="1020" alt="screenshot 2018-03-22 16 55 48" src="https://user-images.githubusercontent.com/12478169/37778157-ea8116f6-2df1-11e8-945e-d2a860565ee9.png">

**Comment by m4rc1e** [comment]
You're looking at my own google/fonts fork which I treat as a sandbox. You can't send anything there.

Just upload your latest changes to this master repo and I will retry.

**Comment by Gue3bara** [comment]
@m4rc1e then that is done issues are solved and uploaded
