### ISSUE TITLE
Three Arabic letters doesn't exist in the font design

### ISSUE THREAD

**Issue by Oxibug** [Gue3bara/Cairo#35]
Hi Pal,

The font design doesn't have very important three Arabic letters...

1. **ى** - (Ya) - Is same as { **ي** } BUT without dots at the bottom and this letter always come at the end of the word. - Example { **أقصى** }

2. **ئ** - Is same as { **ى** } BUT it has { Hamza } above - Example { **سيئ** }

3. **ة** - (Circled - Ta) Is same as { **ه** } BUT it has two dots above - Example { **شجرة** }

[Example Image](https://awscdn.oxibug.com/cdn/wp-content/uploads/2018/09/Font-Cairo.png)

Thanks for your great font.

**Comment by Gue3bara** [comment]
I don't know what would be the reason behind your weird bug but maybe clear your browser cache because this is not an issue in the font itself as you can see below 
<img width="1010" alt="screenshot 2018-09-17 11 31 52" src="https://user-images.githubusercontent.com/12478169/45615633-6a27e080-ba6d-11e8-950b-b5fac7a1fb61.png">
